name: test
on:
    workflow_dispatch:
    pull_request_target:
        types:
            - opened
            - synchronize
        branches:
            - main
        paths:
            - "src/**"
            - "jest.config.[jt]s"
            - "tsconfig.json"
            - "package.json"
jobs:
    main:
        runs-on: ubuntu-latest
        environment: ABYSSERS_TEST_ENV
        steps:
            - name: "[Print Context]"
              env:
                  GITHUB_CONTEXT: ${{ toJSON(github) }}
              run: echo $GITHUB_CONTEXT
            - name: "[Download Repo]"
              uses: actions/checkout@v2
              with:
                  ref: main
            - name: "[Setup NodeJs]"
              uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: "[Install Dependencies]"
              run: sudo npm install --unsafe-perm=true --allow-root --ignore-scripts
            - name: "[Test]"
              run: npm test
